### ISSUE TITLE
init

### ISSUE THREAD

**Issue by zxdong262** [auto-tel/auto-tel#1]
## initial targets:

- set automatic tel schedules
- dial numbers and read text to the target number
- take records for evaluation

## possible use scenes:
- captcha reader
- Telemarketing system
- auto notification system

## key questions:
- [x] text to voice solution: AWS.Polly
- [x] send voice stream to target: investigating, reading more docs, codes...sip.js/web-phone ...

## roadmap:
- [x] backbones: empty canvas ready, build/pack etc
- [ ] schedule system, make schedules of auto-tel
- [x] text reader
- [x] dial process and process records
- [ ] send msg instead of dial option
- [x] manul dial support
